---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  stale:
    uses: timmo001/workflows/.github/workflows/stale.yml@2fb8b15d5e72caaea35cc5e4541733d87ef66002 # 20261008.0
